name: Python CI for Development branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  build:
    uses: anchoranalysis/anchor-python-cicd/.github/workflows/pr_master.yml@main
    with:
      library-name: anchor-python-visualization
    secrets: inherit
