name: Python CI for Master branch

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  build:
    uses: anchoranalysis/anchor-python-cicd/.github/workflows/push_master.yml@main
    with:
      library-name: anchor-python-visualization
    secrets: inherit
